---

- name: Creates directory 
  become: true
  file:
    path: ~/dist
    state: directory

- name: Copy files to ec2 instance
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/dist/artifact.tar.gz

- name: Extract file and start server
  become: true
  shell:
    cmd: |
      cd ~/dist
      tar -xvzf artifact.tar.gz
      npm install
      pm2 stop default
      pm2 start npm -- start