---
- name: Creates directory 
  become: true
  file:
    path: ~/dist
    state: directory

- name: Copy files to ec2 instance
  become: true
  copy:
    src: ../../artifact.tar.gz
    dest: ~/dist

- name: Extract file and start server
  become: true
  shell:
    cmd: |
      cd ~/dist
      tar -xvzf artifact.tar.gz
      npm install
      pm2 stop default
      pm2 start npm -- start





