---
- name: Creates directory n
  file:
    path: ~/node_modules
    state: directory

- name: Creates directory d
  file:
    path: ~/dist
    state: directory

- name: Unarchive Backend
  unarchive:
    src: dist.tar.gz
    dest: /home/ubuntu/dist/
    
- name: Copy and unarchive node_modules
  unarchive:
    src: node_modules.tar.gz
    dest: /home/ubuntu/node_modules/

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i
- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"
- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save