---
---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory n
  file:
    path: ~/node_modules
    state: directory

- name: Creates directory d
  file:
    path: ~/dist
    state: directory

- name: Unarchive Backend
  unarchive:
    src: dist.tar.gz
    dest: /home/ubuntu/dist/
    
- name: Copy and unarchive node_modules
  unarchive:
    src: node_modules.tar.gz
    dest: /home/ubuntu/node_modules/

- name: "start app"
  shell: |       
      pm2 start npm -f ./main.js -- run start
  args: 
    chdir: /home/ubuntu/dist/

- name: "List processes"
  shell: |      
      pm2 list
  register: pm2_result 

- name: "Print in the debug console"
  debug:
    var: pm2_result.stdout_lines

